import { type ReactNode } from 'react';
import { EmotionCache } from '@contact-app/theme';

export const metadata = {
  title: 'Welcome to app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <EmotionCache>
      <html lang="en">
        <body>{children}</body>
      </html>
    </EmotionCache>
  );
}
