import { type ReactNode } from 'react';
import { EmotionCache } from '@contact-app/theme';
import { fetchAllContacts } from '../lib/actions';

export const metadata = {
  title: 'Welcome to app',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const data = await fetchAllContacts();

  console.log('---> layout.tsx, line:15', data);

  return (
    <EmotionCache>
      <html lang="en">
        <body>{children}</body>
      </html>
    </EmotionCache>
  );
}
