import { type ReactNode } from 'react';
import { EmotionCache } from '@contact-app/theme';

export const metadata = {
  title: 'Welcome to app',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const response = await fetch('http://localhost:3000/api/contacts');
  const { data } = await response.json();

  console.log('---> layout.tsx, line:15', data);

  return (
    <EmotionCache>
      <html lang="en">
        <body>{children}</body>
      </html>
    </EmotionCache>
  );
}
